/* Auto Generated by Gourd Build System */
#include <map>
#include <string>
#include <tuple>
std::pair<std::string, std::tuple<std::string, std::string, std::string, std::string>> get_my_version();
std::pair<std::string, std::tuple<std::string, std::string, std::string, std::string>> get_my_version(){
std::pair<std::string, std::tuple<std::string, std::string, std::string, std::string>> ver = 
{"utils.openFileTest", {"no_auther", "no_ver", "", ""}};
return std::move(ver);}

std::map<std::string, std::tuple<std::string, std::string, std::string, std::string>> get_components_version();
std::map<std::string, std::tuple<std::string, std::string, std::string, std::string>> get_components_version(){
std::map<std::string, std::tuple<std::string, std::string, std::string, std::string>> ver = {

};return std::move(ver);}
